
version: "3.4"
volumes:
  mysql_database_volume:
  mysql_test_database_volume:
  postgres_database_volume:
  postgres_test_database_volume:
  mongo_database_volume:
  mongo_test_database_volume:

# x-extension fields
x-env_file: &env_file
  env_file:
    - ./config.env

services:
  mysql_database:
    <<: *env_file
    container_name: mysql_database
    volumes:
      - mysql_database_volume:/var/lib/mysql
    image: mysql:5.7
    ports:
      - 4306:3306

  mysql_test_database:
    <<: *env_file
    container_name: mysql_test_database
    volumes:
      - mysql_test_database_volume:/var/lib/mysql
    image: mysql:5.7
    ports:
      - 5306:3306

  postgres_database:
      <<: *env_file
      container_name: postgres_database
      volumes:
        - postgres_database_volume:/var/lib/postgresql/data/
      image: postgres:10
      ports:
        - 5432:5432

  postgres_test_database:
    <<: *env_file
    container_name: postgres_test_database
    volumes:
      - postgres_test_database_volume:/var/lib/postgresql/data/
    image: postgres:10
    ports:
      - 6432:5432

  mongo_database:
    <<: *env_file
    container_name: mongo_database
    volumes:
      - mongo_database_volume:/data/db
    image: mongo
    ports:
      - 7017:27017

  mongo_test_database:
    <<: *env_file
    container_name: mongo_test_database
    volumes:
      - mongo_test_database_volume:/data/db
    image: mongo
    ports:
      - 8017:27017
