
version: "3.4"
volumes:
  mysql_database_volume:
  postgres_database_volume:

# x-extension fields
x-env_file: &env_file
  env_file:
    - ./config.env

services:
  mysql_database:
    <<: *env_file
    container_name: mysql_database
    volumes:
      - mysql_database_volume:/var/lib/mysql
    image: mysql:5.7
    ports:
      - 4306:3306

  postgres_database:
      <<: *env_file
      container_name: postgres_database
      volumes:
        - postgres_database_volume:/var/lib/postgresql/data/
      image: postgres:10
      ports:
        - 5432:5432
